ethereum:
  default_network: local

  local:
    host: http://127.0.0.1
    port: 8545

  sepolia:
    infura:
      uri: https://sepolia.infura.io/v3/809b114c339249a5a58cf4d058ab25a9
vyper:
  enable_experimental_codegen: false
  version: 0.4.1  # or whatever exact version you want
  use_docker: false  # optional: set to true if you prefer Docker
  settings:
    optimize: false
